---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: centos
    image: geerlingguy/docker-${MOLECULE_DISTRO:-centos8}-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
  - name: ubuntu
    image: geerlingguy/docker-ubuntu2004-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      /sys/fs/cgroup:/sys/fs/cgroup:ro
    pre_build_image: true
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
